# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=10)),
                ('responsibility', models.TextField()),
                ('work_place', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
