# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160804_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='none', max_length=50)),
                ('category', models.CharField(blank=True, default='none', max_length=15)),
                ('shape', models.CharField(blank=True, default=0, max_length=30)),
                ('diameter', models.FloatField(blank=True, default=0)),
                ('length', models.FloatField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
