# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=5)),
                ('shape', models.CharField(max_length=30)),
                ('diameter', models.DecimalField(decimal_places=5, max_digits=10)),
                ('length', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('patronym', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('deliverable', models.BooleanField()),
                ('delivery_type', models.CharField(choices=[('\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u043e\u043c', '\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u043e\u043c'), ('\u0430\u0432\u0442\u043e\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u043c', '\u0430\u0432\u0442\u043e\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u043c'), ('\u0436\u0435\u043b\u0435\u0437\u043d\u043e\u0439 \u0434\u043e\u0440\u043e\u0433\u043e\u0439', '\u0436\u0435\u043b\u0435\u0437\u043d\u043e\u0439 \u0434\u043e\u0440\u043e\u0433\u043e\u0439')], max_length=5)),
                ('station_code', models.CharField(max_length=30)),
                ('scrap_type', models.CharField(max_length=30)),
                ('scrap_media', models.FileField(upload_to='uploads/purchases')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('patronym', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_type', models.CharField(choices=[('\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u043e\u043c', '\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u043e\u043c'), ('\u0430\u0432\u0442\u043e\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u043c', '\u0430\u0432\u0442\u043e\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u043c'), ('\u0436\u0435\u043b\u0435\u0437\u043d\u043e\u0439 \u0434\u043e\u0440\u043e\u0433\u043e\u0439', '\u0436\u0435\u043b\u0435\u0437\u043d\u043e\u0439 \u0434\u043e\u0440\u043e\u0433\u043e\u0439')], max_length=20)),
                ('document', models.FileField(upload_to='uploads/sales')),
                ('message', models.TextField()),
                ('product', models.ManyToManyField(to='requests.Product')),
            ],
        ),
    ]
