# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20160730_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('patronym', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_type', models.CharField(choices=[('\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u043e\u043c', '\u0441\u0430\u043c\u043e\u0432\u044b\u0432\u043e\u0437\u043e\u043c'), ('\u0430\u0432\u0442\u043e\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u043c', '\u0430\u0432\u0442\u043e\u0442\u0440\u0430\u043d\u0441\u043f\u043e\u0440\u0442\u043e\u043c'), ('\u0436\u0435\u043b\u0435\u0437\u043d\u043e\u0439 \u0434\u043e\u0440\u043e\u0433\u043e\u0439', '\u0436\u0435\u043b\u0435\u0437\u043d\u043e\u0439 \u0434\u043e\u0440\u043e\u0433\u043e\u0439')], max_length=20)),
                ('document', models.FileField(upload_to='uploads/sales')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='sale_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.Sale_Order'),
        ),
        migrations.AddField(
            model_name='sale_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.Product'),
        ),
    ]
