# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20160804_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale_Item',
            new_name='SaleItem',
        ),
        migrations.RenameModel(
            old_name='Sale_Order',
            new_name='SaleOrder',
        ),
    ]
