# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20160804_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
